name: haskell-url-shortener
version: 0.1.0.0
github: "joelfisch/haskell-url-shortener"
license: BSD3
author: "Joel Fisch"

extra-source-files:
  - README.md

description: Please see the README on GitHub at <https://github.com/joelfisch/haskell-url-shortener#readme>

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - servant-server
  - wai
  - warp
  - persistent
  - persistent-sqlite
  - persistent-template
  - text
  - validity
  - validity-text
  - monad-logger
  - regex-tdfa
  - raw-strings-qq

library:
  source-dirs: src

executables:
  haskell-url-shortener-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base
      - haskell-url-shortener

tests:
  haskell-url-shortener-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base
      - haskell-url-shortener
      - hspec
      - hspec-wai
      - hspec-wai-json
      - QuickCheck
      - genvalidity-hspec
      - http-types
      - bytestring
      - wai-extra
