name: "Stack Build"
on:
  pull_request:
  push:
    branches: 
      - development
      - master

jobs:
  stack:
    name: stack / ghc ${{ matrix.ghc }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        stack: ["2.7.1"]
        ghc: ["8.10.4"]

    steps:
    - uses: actions/checkout@v2
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/master'

    - uses: actions/setup-haskell@v1.1.3
      name: Setup Haskell Stack
      with:
        ghc-version: ${{ matrix.ghc }}
        stack-version: ${{ matrix.stack }}

    - uses: actions/cache@v1
      name: Cache ~/.stack
      with:
        path: |
          ~/.stack
          .stack-work
        key: ${{ runner.os }}-${{ matrix.ghc }}-stack

    - name: Build dependencies
      run: |
        stack build --system-ghc --only-dependencies

    - name: Test
      run: |
        stack test --system-ghc

    - name: Build
      run: |
        stack install --system-ghc --local-bin-path="."
        echo "----------------"
        ls -l
        echo "----------------"
        stack path --local-install-root
        ls -l $(stack path --local-install-root)
        echo "----------------"
        stack path --local-bin-path
        ls -l $(stack path --local-bin-path)
        echo "----------------"
        mv haskell-url-shortener-exe url-shortener
        echo "----------------"

    - name: Log in to GitHub Docker Registry
      if: github.event.ref == 'refs/heads/master'
      uses: docker/login-action@v1
      with:
        registry: docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build container image
      if: github.event.ref == 'refs/heads/master'
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          docker.pkg.github.com/${{ github.repository }}/haskell-url-shortener:${{ github.sha }}
          docker.pkg.github.com/${{ github.repository }}/haskell-url-shortener:latest
